version: "3"

services:
  back:
    build: ./back/
    container_name: website-back
    restart: always
    volumes:
      - ./back/src:/usr/src/app/src
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      FRONT_URI: "http://localhost:3000"
    command: "npm run start"
  #  depends_on:
  #    - db
  front:
    build: ./front/
    container_name: website-front
    restart: always
    volumes:
      - ./front/components:/usr/src/app/components
      - ./front/pages:/usr/src/app/pages
      - ./front/store:/usr/src/app/store
    ports:
        - "3000:3000"
    environment:
      PORT: 3000
      BACK_URI: "http://localhost:4000"
    command: "npm run dev"
    depends_on:
      - back
  #db:
  #  image: postgres
  #  ports:
  #    - "5432:5432"
  #  environment:
  #    POSTGRES_PASSWORD: password
  #    PGDATA: /tmp