version: "3"

services:
  back:
    build: ./back/
    container_name: website-back
    restart: always
    volumes:
      - ./back/src:/usr/src/app/src
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      FRONT_URI: "http://localhost:3000"
    command: "npm run start"
    depends_on:
      - db
  front:
    build: ./front/
    container_name: website-front
    restart: always
    volumes:
      - ./front/components:/usr/src/app/components
      - ./front/layouts:/usr/src/app/layouts
      - ./front/pages:/usr/src/app/pages
      - ./front/store:/usr/src/app/store
    ports:
        - "3000:3000"
    environment:
      PORT: 3000
      BACK_URI: "http://localhost:4000"
    command: "npm run dev"
    depends_on:
      - back
  db:
    image: postgres
    container_name: website-db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
      - ./postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file:
      - postgres/database.env